# Used to build System.Web with trace support
NANT=$(RUNTIME) ../../nant/NAnt.exe
MAKE_GNU=$(MAKE) -f makefile.gnu -C .
BUILDPLATFORM=uname | grep CYGWIN 2> /dev/null
all:
	@echo "Building System.Web.dll with Trace enabled."
	($(BUILDPLATFORM) && $(NANT) trace) || \
		$(MAKE_GNU) LIB_FLAGS="/d:TRACE /d:WEBTRACE -r corlib -r System -r System.Drawing -r System.Xml"

clean:
	($(BUILDPLATFORM) && $(NANT) clean) || $(MAKE_GNU) clean

